// Material Symbols → Phosphor icon mapping
// Each entry: Material Symbol name → Phosphor React component import name

import {
  Chats,
  ChartBar,
  SquaresFour,
  GearSix,
  PencilSimple,
  PushPin,
  Download,
  Trash,
  MagnifyingGlass,
  Sun,
  Moon,
  Desktop,
  CaretLeft,
  DotsThree,
  Info,
  FileText,
  X,
  StopCircle,
  ArrowUp,
  Plus,
  UploadSimple,
  ListChecks,
  Exam,
  ArrowsClockwise,
  Copy,
  Export,
  Eye,
  EyeSlash,
  Check,
  CheckCircle,
  WarningCircle,
  ArrowRight,
  PlayCircle,
  ThumbsUp,
  ThumbsDown,
  ChatsCircle,
  ShareNetwork,
  Users,
  BookmarkSimple,
  Coin,
  Subtitles,
  TrendUp,
  Clock,
  Tag,
  TextAa,
  ChartLineUp,
  ChartPie,
  ChartPolar,
  ChartScatter,
  Brain,
  Trophy,
  Lightbulb,
  Database,
  Person,
  HourglassSimple,
  Video,
  FunnelSimple,
  TextAlignLeft,
  Paperclip,
  Table,
  File,
  Note,
  Sparkle,
  MagicWand,
  Palette,
  Screencast,
  Hash,
  ChatCircle,
  PushPinSimple,
  StackSimple,
  ArrowDown,
  ArrowUpRight,
} from '@phosphor-icons/react'
import type { ComponentType } from 'react'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const iconMap: Record<string, ComponentType<any>> = {
  // Navigation & UI
  chat_bubble: Chats,
  analytics: ChartBar,
  grid_view: SquaresFour,
  settings: GearSix,
  edit: PencilSimple,
  push_pin: PushPin,
  download: Download,
  delete: Trash,
  search: MagnifyingGlass,
  light_mode: Sun,
  dark_mode: Moon,
  computer: Desktop,
  chevron_left: CaretLeft,
  more_horiz: DotsThree,
  info: Info,
  close: X,
  stop: StopCircle,
  add: Plus,
  check: Check,
  check_circle: CheckCircle,
  error: WarningCircle,
  arrow_up: ArrowUp,
  arrow_upward: ArrowUp,
  arrow_down: ArrowDown,
  arrow_downward: ArrowDown,
  arrow_right: ArrowRight,
  arrow_up_right: ArrowUpRight,

  // Files & Content
  description: FileText,
  upload_file: UploadSimple,
  edit_note: Note,
  title: TextAlignLeft,
  checklist: ListChecks,
  compare: Exam,
  content_copy: Copy,
  ios_share: Export,
  visibility: Eye,
  visibility_off: EyeSlash,
  dashboard: StackSimple,
  text_fields: TextAa,
  text_snippet: File,

  // Media & Playback
  play_circle: PlayCircle,
  smart_display: Screencast,
  music_note: Palette,
  style: Hash,
  videocam: Video,
  video_library: StackSimple,

  // Actions & Feedback
  thumb_up: ThumbsUp,
  thumb_down: ThumbsDown,
  refresh: ArrowsClockwise,
  auto_awesome: Sparkle,
  lightbulb: Lightbulb,
  tips_and_updates: MagicWand,

  // Data & Analytics
  trending_up: TrendUp,
  schedule: Clock,
  category: Tag,
  share: ShareNetwork,
  comment: ChatsCircle,
  group: Users,
  bookmark: BookmarkSimple,
  paid: Coin,
  subtitles: Subtitles,
  show_chart: ChartLineUp,
  pie_chart: ChartPie,
  radar: ChartPolar,
  scatter_plot: ChartScatter,
  psychology: Brain,
  leaderboard: Trophy,
  database: Database,
  person: Person,
  label: Tag,
  hourglass_empty: HourglassSimple,
  tune: FunnelSimple,

  // Misc
  push_pin_simple: PushPinSimple,
  tag: Tag,
  chat: ChatCircle,
  table_chart: Table,
  paperclip: Paperclip,
}

export default iconMap
